version: '3'

services:
  auth_db:
    image: postgres:latest
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_AUTH_USER}
      POSTGRES_PASSWORD: ${PG_AUTH_PASSWORD}
      POSTGRES_DB: ${PG_AUTH_DB}
    expose:
      - 5432
  auth_service:
    image: my-game-auth:latest
    command: bash -c 'while !</dev/tcp/auth_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8956'
    build: ./services/auth/
    volumes:
      - ./services/auth/:/auth/
    env_file:
      - .admin.env
      - .env
      - .keys.env
    expose:
      - 8956
    depends_on:
      - auth_db
  bot_service:
    image: my-game-bot:latest
    command: python app/main.py
    build: ./services/bot/
    volumes:
      - ./services/bot/:/bot/
    env_file:
      - .env
      - .telegram.env
    depends_on:
      - rabbit
  logic_db:
    image: postgres:latest
    volumes:
      - postgres_data_logic:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_LOGIC_USER}
      POSTGRES_PASSWORD: ${PG_LOGIC_PASSWORD}
      POSTGRES_DB: ${PG_LOGIC_DB}
    expose:
      - 5432
  logic_service:
    image: my-game-logic:latest
    command: bash -c 'while !</dev/tcp/logic_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 14961'
    build: ./services/logic/
    volumes:
      - ./services/logic/:/logic/
    env_file:
      - .env
      - .site.env
    expose:
      - 14961
    depends_on:
      - logic_db
  rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmq_data:/data

volumes:
  postgres_data_test:
  postgres_data_auth:
  postgres_data_logic:

  rabbitmq_data:
