version: '3'

services:
  auth_db:
    image: postgres:latest
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_AUTH_USER}
      POSTGRES_PASSWORD: ${PG_AUTH_PASSWORD}
      POSTGRES_DB: ${PG_AUTH_DB}
    expose:
      - 5432
    restart: on-failure
  auth_service:
    image: my-game-auth:latest
    command: bash -c 'while !</dev/tcp/auth_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8956'
    build: ./services/auth/
    volumes:
      - ./services/auth/:/auth/
    env_file:
      - .admin.env
      - .env
      - .keys.env
    ports:
      - '8956:8956'
    depends_on:
      - auth_db
    restart: on-failure
  bot_service:
    image: my-game-bot:latest
    command: python app/main.py
    build: ./services/bot/
    volumes:
      - ./services/bot/:/bot/
    env_file:
      - .env
      - .telegram.env
    depends_on:
      - rabbit
    restart: on-failure
  api_db:
    image: postgres:latest
    volumes:
      - postgres_data_api:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_API_USER}
      POSTGRES_PASSWORD: ${PG_API_PASSWORD}
      POSTGRES_DB: ${PG_API_DB}
    expose:
      - 5432
    restart: on-failure
  api_service:
    image: my-game-api:latest
    command: bash -c 'while !</dev/tcp/api_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 14961'
    build: ./services/api/
    volumes:
      - ./services/api/:/api/
    env_file:
      - .admin.env
      - .env
      - .site.env
    ports:
      - '14961:14961'
    depends_on:
      - api_db
      - auth_service
    restart: on-failure
  handler_db:
    image: postgres:latest
    volumes:
      - postgres_data_handler:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_HANDLER_USER}
      POSTGRES_PASSWORD: ${PG_HANDLER_PASSWORD}
      POSTGRES_DB: ${PG_HANDLER_DB}
    expose:
      - 5432
    ports:
      - '5432:5432'
    restart: on-failure
  handler_service:
    image: my-game-handler:latest
    command: bash -c "while !</dev/tcp/handler_db/5432; do sleep 1; done; python app/main.py"
    build: ./services/handler
    volumes:
      - ./services/handler/:/handler
    env_file:
      - .admin.env
      - .env
      - .site.env
      - .telegram.env
    depends_on:
      - handler_db
      - api_service
    ports:
      - '8080:8080'
    restart: on-failure
  rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmq_data:/data
volumes:
  postgres_data_api:
  postgres_data_auth:
  postgres_data_handler:

  rabbitmq_data:
