version: '3'

services:
  auth_db:
    image: postgres:latest
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_AUTH_USER}
      POSTGRES_PASSWORD: ${PG_AUTH_PASSWORD}
      POSTGRES_DB: ${PG_AUTH_DB}
    expose:
      - 5432
  auth_service:
    image: my-game-auth:latest
    command: bash -c 'while !</dev/tcp/auth_db/5432; do sleep 1; done; uvicorn main:app --reload --host 0.0.0.0 --port 8080'
    build: ./services/auth/
    volumes:
      - ./services/auth/app/:/app/
    env_file:
      - .admin.env
      - .env
      - .keys.env
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on:
      - rabbitmq_service

  bot_service:
    image: my-game-bot:latest
    command: python main.py
    build: ./services/bot/
    volumes:
      - ./services/bot/app/:/app/
    env_file:
      - .env
      - .telegram.env
    depends_on:
      - rabbitmq_service
  rabbitmq_service:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmq_data:/data

volumes:
  postgres_data_auth:
  rabbitmq_data:
