version: '3'

services:
  api_db:
    image: postgres:latest
    volumes:
      - postgres_data_api:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_API_USER}
      POSTGRES_PASSWORD: ${PG_API_PASSWORD}
      POSTGRES_DB: ${PG_API_DB}
    expose:
      - 5432
    restart: on-failure
  api_service:
    image: my-game-api:latest
    build: ./services/api/
    volumes:
      - ./services/api/:/api/
    env_file:
      - .admin.env
      - .env
    depends_on:
      - api_db
    restart: on-failure
  bot_service:
    image: my-game-bot:latest
    build: ./services/bot/
    volumes:
      - ./services/bot/:/bot/
    env_file:
      - .env
      - .telegram.env
    depends_on:
      - rabbit
    restart: on-failure
  handler_db:
    image: postgres:latest
    volumes:
      - postgres_data_handler:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_HANDLER_USER}
      POSTGRES_PASSWORD: ${PG_HANDLER_PASSWORD}
      POSTGRES_DB: ${PG_HANDLER_DB}
    expose:
      - 5432
    restart: on-failure
  handler_service:
    image: my-game-handler:latest
    build: ./services/handler
    volumes:
      - ./services/handler/:/handler
    env_file:
      - .admin.env
      - .env
      - .site.env
      - .telegram.env
    depends_on:
      - handler_db
    restart: on-failure
  rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmq_data:/data
volumes:
  postgres_data_api:
  postgres_data_handler:

  rabbitmq_data:
